In [1]:
import pandas as pd

In [2]:
train=pd.read_csv('train.csv')

In [3]:
test=pd.read_csv('test.csv')

In [4]:
train

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
5,8,NaN,NaN,#RockyFire Update => California Hwy. 20 closed...,1
6,10,NaN,NaN,#flood #disaster Heavy rain causes flash flood...,1
7,13,NaN,NaN,I'm on top of the hill and I can see a fire in...,1
8,14,NaN,NaN,There's an emergency evacuation happening now ...,1
9,15,NaN,NaN,I'm afraid that the tornado is coming to our a...,1
10,16,NaN,NaN,Three people died from the heat wave so far,1
11,17,NaN,NaN,Haha South Tampa is getting flooded hah- WAIT ...,1
12,18,NaN,NaN,#raining #flooding #Florida #TampaBay #Tampa 1...,1
13,19,NaN,NaN,#Flood in Bago Myanmar #We arrived Bago,1
14,20,NaN,NaN,Damage to school bus on 80 in multi car crash ...,1
15,23,NaN,NaN,What's up man?,0
16,24,NaN,NaN,I love fruits,0
17,25,NaN,NaN,Summer is lovely,0
18,26,NaN,NaN,My car is so fast,0
19,28,NaN,NaN,What a goooooooaaaaaal!!!!!!,0
20,31,NaN,NaN,this is ridiculous....,0
21,32,NaN,NaN,London is cool ;),0
22,33,NaN,NaN,Love skiing,0
23,34,NaN,NaN,What a wonderful day!,0
24,36,NaN,NaN,LOOOOOOL,0
25,37,NaN,NaN,No way...I can't eat that shit,0
26,38,NaN,NaN,Was in NYC last week!,0
27,39,NaN,NaN,Love my girlfriend,0
28,40,NaN,NaN,Cooool :),0
29,41,NaN,NaN,Do you like pasta?,0
...,...,...,...,...,...
7583,10835,NaN,NaN,Pic of 16yr old PKK suicide bomber who detonat...,1
7584,10837,NaN,NaN,These boxes are ready to explode! Exploding Ki...,0
7585,10839,NaN,NaN,Calgary Police Flood Road Closures in Calgary....,1
7586,10840,NaN,NaN,#Sismo DETECTADO #JapÌ_n 15:41:07 Seismic inte...,1
7587,10841,NaN,NaN,Sirens everywhere!,0
7588,10842,NaN,NaN,BREAKING: #ISIS claims responsibility for mosq...,1
7589,10843,NaN,NaN,Omg earthquake,1
7590,10844,NaN,NaN,SEVERE WEATHER BULLETIN No. 5 FOR: TYPHOON ÛÏ...,1
7591,10846,NaN,NaN,Heat wave warning aa? Ayyo dei. Just when I pl...,1
7592,10847,NaN,NaN,An IS group suicide bomber detonated an explos...,1
7593,10848,NaN,NaN,I just heard a really loud bang and everyone i...,0
7594,10849,NaN,NaN,A gas thing just exploded and I heard screams ...,1
7595,10850,NaN,NaN,NWS: Flash Flood Warning Continued for Shelby ...,1
7596,10851,NaN,NaN,RT @LivingSafely: #NWS issues Severe #Thunders...,1
7597,10852,NaN,NaN,#??? #?? #??? #??? MH370: Aircraft debris foun...,1
7598,10853,NaN,NaN,Father-of-three Lost Control of Car After Over...,1
7599,10854,NaN,NaN,1.3 #Earthquake in 9Km Ssw Of Anza California ...,1
7600,10855,NaN,NaN,Evacuation order lifted for town of Roosevelt:...,1
7601,10859,NaN,NaN,#breaking #LA Refugio oil spill may have been ...,1
7602,10860,NaN,NaN,a siren just went off and it wasn't the Forney...,1
7603,10862,NaN,NaN,Officials say a quarantine is in place at an A...,1
7604,10863,NaN,NaN,#WorldNews Fallen powerlines on G:link tram: U...,1
7605,10864,NaN,NaN,on the flip side I'm at Walmart and there is a...,1
7606,10866,NaN,NaN,Suicide bomber kills 15 in Saudi security site...,1
7607,10867,NaN,NaN,#stormchase Violent Record Breaking EF-5 El Re...,1
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [5]:
test

,id,keyword,location,text
0,0,NaN,NaN,Just happened a terrible car crash
1,2,NaN,NaN,"Heard about #earthquake is different cities, s..."
2,3,NaN,NaN,"there is a forest fire at spot pond, geese are..."
3,9,NaN,NaN,Apocalypse lighting. #Spokane #wildfires
4,11,NaN,NaN,Typhoon Soudelor kills 28 in China and Taiwan
5,12,NaN,NaN,We're shaking...It's an earthquake
6,21,NaN,NaN,They'd probably still show more life than Arse...
7,22,NaN,NaN,Hey! How are you?
8,27,NaN,NaN,What a nice hat?
9,29,NaN,NaN,Fuck off!
10,30,NaN,NaN,No I don't like cold!
11,35,NaN,NaN,NOOOOOOOOO! Don't do that!
12,42,NaN,NaN,No don't tell me that!
13,43,NaN,NaN,What if?!
14,45,NaN,NaN,Awesome!
15,46,ablaze,London,Birmingham Wholesale Market is ablaze BBC News...
16,47,ablaze,Niall's place | SAF 12 SQUAD |,@sunkxssedharry will you wear shorts for race ...
17,51,ablaze,NIGERIA,#PreviouslyOnDoyinTv: Toke MakinwaÛªs marriag...
18,58,ablaze,Live On Webcam,Check these out: http://t.co/rOI2NSmEJJ http:/...
19,60,ablaze,"Los Angeles, Califnordia",PSA: IÛªm splitting my personalities.\n\n?? t...
20,69,ablaze,threeonefive.,beware world ablaze sierra leone &amp; guap.
21,70,ablaze,Washington State,Burning Man Ablaze! by Turban Diva http://t.co...
22,72,ablaze,"Whoop Ass, Georgia",Not a diss song. People will take 1 thing and ...
23,75,ablaze,India,Rape victim dies as she sets herself ablaze: A...
24,84,ablaze,NaN,SETTING MYSELF ABLAZE http://t.co/6vMe7P5XhC
25,87,ablaze,"scarborough, ontario",@CTVToronto the bins in front of the field by ...
26,88,ablaze,NaN,#nowplaying Alfons - Ablaze 2015 on Puls Radio...
27,90,ablaze,"121 N La Salle St, Suite 500",'Burning Rahm': Let's hope City Hall builds a ...
28,94,ablaze,Wandering,@PhilippaEilhart @DhuBlath hurt but her eyes a...
29,99,accident,"Homewood, PA",Accident cleared in #PaTurnpike on PATP EB bet...
...,...,...,...,...
3233,10756,wreckage,Mumbai,Wreckage 'Conclusively Confirmed' as From MH37...
3234,10757,wreckage,NaN,#science Now that a piece of wreckage from fli...
3235,10758,wreckage,India,Wreckage 'Conclusively Confirmed' as From MH37...
3236,10761,wreckage,Mumbai,Wreckage 'Conclusively Confirmed' as From MH37...
3237,10762,wreckage,Canada,TOP STORY: wreckage from #MH370 officially con...
3238,10773,wreckage,NaN,Wreckage 'Conclusively Confirmed' as From MH37...
3239,10778,wreckage,Mumbai,Wreckage 'Conclusively Confirmed' as From MH37...
3240,10781,wreckage,our galaxy,RT @australian Debris found on an Indian Ocean...
3241,10791,wrecked,Sunny Southern California,Cramer: Iger's 3 words that wrecked Disney's s...
3242,10792,wrecked,"Plymouth, England",Almost *wrecked* my van the other day because ...
3243,10796,wrecked,Deep in the heart of LibLand,'What manner of human being would parcel out a...
3244,10797,wrecked,NaN,@Nathan26_RFC thought you said Saturday night ...
3245,10801,wrecked,"Canada,Ontario",I just wanna ease your mind and make you feel ...
3246,10804,wrecked,Love Reiss,@yakubOObs think he deactivated because his no...
3247,10806,wrecked,Seattle Washington,RT CNBC '3 words from Disney CEO Bob Iger wrec...
3248,10807,wrecked,Acey mountain islanddåÇTorontoåÈ,Smackdown tyme this should put me in a good mo...
3249,10816,wrecked,los angeles,@thrillhho jsyk I haven't stopped thinking abt...
3250,10820,wrecked,"Brussels, Belgium",@stighefootball Begovic has been garbage. He g...
3251,10828,wrecked,NaN,Wrecked today got my hattrick ????
3252,10836,NaN,NaN,#Ebola #EbolaOutbreak Ebola Virus: Birmingham ...
3253,10838,NaN,NaN,Malaysian PM confirms debris is from missing f...
3254,10845,NaN,NaN,Officials: Alabama home quarantined over possi...
3255,10856,NaN,NaN,See the 16yr old PKK suicide bomber who detona...
3256,10857,NaN,NaN,To conference attendees! The blue line from th...
3257,10858,NaN,NaN,The death toll in a #IS-suicide car bombing on...
3258,10861,NaN,NaN,EARTHQUAKE SAFETY LOS ANGELES ÛÒ SAFETY FASTE...
3259,10865,NaN,NaN,Storm in RI worse than last hurricane. My city...
3260,10868,NaN,NaN,Green Line derailment in Chicago http://t.co/U...
3261,10874,NaN,NaN,MEG issues Hazardous Weather Outlook (HWO) htt...
3262,10875,NaN,NaN,#CityofCalgary has activated its Municipal Eme...

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
id          7613 non-null int64
keyword     7552 non-null object
location    5080 non-null object
text        7613 non-null object
target      7613 non-null int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

In [7]:
train.isnull().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [8]:
train.drop('location',axis=1,inplace=True)

In [9]:
train.dropna(inplace=True)

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le=LabelEncoder()

In [12]:
train.keyword=le.fit_transform(train.keyword)

In [13]:
train['keyword'].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220])

In [14]:
train

,id,keyword,text,target
31,48,0,@bbcmtd Wholesale Markets ablaze http://t.co/l...,1
32,49,0,We always try to bring the heavy. #metal #RT h...,0
33,50,0,#AFRICANBAZE: Breaking news:Nigeria flag set a...,1
34,52,0,Crying out for more! Set me ablaze,0
35,53,0,On plus side LOOK AT THE SKY LAST NIGHT IT WAS...,0
36,54,0,@PhDSquares #mufc they've built so much hype a...,0
37,55,0,INEC Office in Abia Set Ablaze - http://t.co/3...,1
38,56,0,Barbados #Bridgetown JAMAICA ÛÒ Two cars set ...,1
39,57,0,Ablaze for you Lord :D,0
40,59,0,Check these out: http://t.co/rOI2NSmEJJ http:/...,0
41,61,0,on the outside you're ablaze and alive\nbut yo...,0
42,62,0,Had an awesome time visiting the CFC head offi...,0
43,63,0,SOOOO PUMPED FOR ABLAZE ???? @southridgelife,0
44,64,0,I wanted to set Chicago ablaze with my preachi...,0
45,65,0,I gained 3 followers in the last week. You? Kn...,0
46,66,0,How the West was burned: Thousands of wildfire...,1
47,67,0,Building the perfect tracklist to life leave t...,0
48,68,0,Check these out: http://t.co/rOI2NSmEJJ http:/...,0
49,71,0,First night with retainers in. It's quite weir...,0
50,73,0,Deputies: Man shot before Brighton home set ab...,1
51,74,0,Man wife get six years jail for setting ablaze...,1
52,76,0,SANTA CRUZ ÛÓ Head of the St Elizabeth Police...,0
53,77,0,Police: Arsonist Deliberately Set Black Church...,1
54,78,0,Noches El-Bestia '@Alexis_Sanchez: happy to se...,0
55,79,0,#Kurds trampling on Turkmen flag later set it ...,1
56,80,0,TRUCK ABLAZE : R21. VOORTREKKER AVE. OUTSIDE O...,1
57,81,0,Set our hearts ablaze and every city was a gif...,0
58,82,0,They sky was ablaze tonight in Los Angeles. I'...,0
59,83,0,How the West was burned: Thousands of wildfire...,1
60,85,0,Revel in yours wmv videos by means of mac fare...,0
...,...,...,...,...
7553,10798,220,#news Cramer: Iger's 3 words that wrecked Disn...,0
7554,10799,220,James Kunstler: How bad architecture wrecked c...,0
7555,10800,220,http://t.co/DeQQOpSP4f: Iger's 3 words that wr...,0
7556,10802,220,The Twitter update pretty much wrecked the app,0
7557,10803,220,You wrecked me. Never felt so low in my life. ...,0
7558,10805,220,coleslaw #wrecked http://t.co/sijNBmCZIJ,0
7559,10808,220,300K exotic car wrecked in train accident \nht...,1
7560,10809,220,The twins pitcher's ego is now WRECKED,0
7561,10810,220,@Tunes_WGG lol. U got wrecked,0
7562,10811,220,you wrecked my whole world,0
7563,10812,220,I wrecked my stomach help,0
7564,10813,220,@__ohhmyjoshh @stevenrulles he not gonna be th...,0
7565,10814,220,Wrecked tired but not gonna be asleep before 3??,0
7566,10815,220,http://t.co/qVx0VQTPz0 Cramer: Iger's 3 words ...,0
7567,10817,220,Wrecked emotions.,0
7568,10818,220,The Riddler would be the best early-exit prima...,0
7569,10819,220,@marynmck That's beyond adorable. I hope it wo...,0
7570,10821,220,Cramer: Iger's 3 words that wrecked Disney's s...,0
7571,10822,220,@Caitsroberts see U the night wee bArra to get...,0
7572,10823,220,@Kirafrog @mount_wario Did you get wrecked again?,1
7573,10824,220,Had an awesome time gettin wrecked at bowling ...,0
7574,10825,220,Cramer: 3 words that wrecked DIS stock - http:...,0
7575,10826,220,On the bright side I wrecked http://t.co/uEa0t...,0
7576,10827,220,He just wrecked all of you http://t.co/y46isyZkC8,0
7577,10829,220,@widda16 ... He's gone. You can relax. I thoug...,0
7578,10830,220,@jt_ruff23 @cameronhacker and I wrecked you both,0
7579,10831,220,Three days off from work and they've pretty mu...,0
7580,10832,220,#FX #forex #trading Cramer: Iger's 3 words tha...,0
7581,10833,220,@engineshed Great atmosphere at the British Li...,0
7582,10834,220,Cramer: Iger's 3 words that wrecked Disney's s...,0

In [15]:
import nltk
from nltk.corpus import stopwords
import string

In [16]:
def text_process(text):
    

    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [17]:
train['text']=train['text'].apply(text_process).astype(str).apply(lambda x: x.lower())

In [18]:
train['text'] = train['text'].str.replace('http\S+|www.\S+', '', case=False)

In [19]:
train['text'][31]

"['bbcmtd', 'wholesale', 'markets', 'ablaze', '"

In [20]:
train

,id,keyword,text,target
31,48,0,"['bbcmtd', 'wholesale', 'markets', 'ablaze', '",1
32,49,0,"['always', 'try', 'bring', 'heavy', 'metal', '...",0
33,50,0,"['africanbaze', 'breaking', 'newsnigeria', 'fl...",1
34,52,0,"['crying', 'set', 'ablaze']",0
35,53,0,"['plus', 'side', 'look', 'sky', 'last', 'night...",0
36,54,0,"['phdsquares', 'mufc', 'theyve', 'built', 'muc...",0
37,55,0,"['inec', 'office', 'abia', 'set', 'ablaze', '",1
38,56,0,"['barbados', 'bridgetown', 'jamaica', '\x89ûò'...",1
39,57,0,"['ablaze', 'lord']",0
40,59,0,"['check', ' ' ' ' 'nsfw']",0
41,61,0,"['outside', 'youre', 'ablaze', 'alive', 'youre...",0
42,62,0,"['awesome', 'time', 'visiting', 'cfc', 'head',...",0
43,63,0,"['soooo', 'pumped', 'ablaze', 'southridgelife']",0
44,64,0,"['wanted', 'set', 'chicago', 'ablaze', 'preach...",0
45,65,0,"['gained', '3', 'followers', 'last', 'week', '...",0
46,66,0,"['west', 'burned', 'thousands', 'wildfires', '...",1
47,67,0,"['building', 'perfect', 'tracklist', 'life', '...",0
48,68,0,"['check', ' ' ' ' 'nsfw']",0
49,71,0,"['first', 'night', 'retainers', 'quite', 'weir...",0
50,73,0,"['deputies', 'man', 'shot', 'brighton', 'home'...",1
51,74,0,"['man', 'wife', 'get', 'six', 'years', 'jail',...",1
52,76,0,"['santa', 'cruz', '\x89ûó', 'head', 'st', 'eli...",0
53,77,0,"['police', 'arsonist', 'deliberately', 'set', ...",1
54,78,0,"['noches', 'elbestia', 'alexissanchez', 'happy...",0
55,79,0,"['kurds', 'trampling', 'turkmen', 'flag', 'lat...",1
56,80,0,"['truck', 'ablaze', 'r21', 'voortrekker', 'ave...",1
57,81,0,"['set', 'hearts', 'ablaze', 'every', 'city', '...",0
58,82,0,"['sky', 'ablaze', 'tonight', 'los', 'angeles',...",0
59,83,0,"['west', 'burned', 'thousands', 'wildfires', '...",1
60,85,0,"['revel', 'wmv', 'videos', 'means', 'mac', 'fa...",0
...,...,...,...,...
7553,10798,220,"['news', 'cramer', 'igers', '3', 'words', 'wre...",0
7554,10799,220,"['james', 'kunstler', 'bad', 'architecture', '...",0
7555,10800,220,"[' 'igers', '3', 'words', 'wrecked', 'disneys'...",0
7556,10802,220,"['twitter', 'update', 'pretty', 'much', 'wreck...",0
7557,10803,220,"['wrecked', 'never', 'felt', 'low', 'life', 'o...",0
7558,10805,220,"['coleslaw', 'wrecked', '",0
7559,10808,220,"['300k', 'exotic', 'car', 'wrecked', 'train', ...",1
7560,10809,220,"['twins', 'pitchers', 'ego', 'wrecked']",0
7561,10810,220,"['tuneswgg', 'lol', 'u', 'got', 'wrecked']",0
7562,10811,220,"['wrecked', 'whole', 'world']",0
7563,10812,220,"['wrecked', 'stomach', 'help']",0
7564,10813,220,"['ohhmyjoshh', 'stevenrulles', 'gonna', 'think...",0
7565,10814,220,"['wrecked', 'tired', 'gonna', 'asleep', '3']",0
7566,10815,220,"[' 'cramer', 'igers', '3', 'words', 'wrecked',...",0
7567,10817,220,"['wrecked', 'emotions']",0
7568,10818,220,"['riddler', 'would', 'best', 'earlyexit', 'pri...",0
7569,10819,220,"['marynmck', 'thats', 'beyond', 'adorable', 'h...",0
7570,10821,220,"['cramer', 'igers', '3', 'words', 'wrecked', '...",0
7571,10822,220,"['caitsroberts', 'see', 'u', 'night', 'wee', '...",0
7572,10823,220,"['kirafrog', 'mountwario', 'get', 'wrecked']",1
7573,10824,220,"['awesome', 'time', 'gettin', 'wrecked', 'bowl...",0
7574,10825,220,"['cramer', '3', 'words', 'wrecked', 'dis', 'st...",0
7575,10826,220,"['bright', 'side', 'wrecked', '",0
7576,10827,220,"['wrecked', '",0
7577,10829,220,"['widda16', 'hes', 'gone', 'relax', 'thought',...",0
7578,10830,220,"['jtruff23', 'cameronhacker', 'wrecked']",0
7579,10831,220,"['three', 'days', 'work', 'theyve', 'pretty', ...",0
7580,10832,220,"['fx', 'forex', 'trading', 'cramer', 'igers', ...",0
7581,10833,220,"['engineshed', 'great', 'atmosphere', 'british...",0
7582,10834,220,"['cramer', 'igers', '3', 'words', 'wrecked', '...",0

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

In [22]:
from sklearn.model_selection import train_test_split
X=train.drop('target',axis=1)
y=train['target']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=101)

In [23]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('bow', CountVectorizer(analyzer=text_process)),  # strings to token integer counts
    ('tfidf', TfidfTransformer()),  # integer counts to weighted TF-IDF scores
    ('classifier', MultinomialNB()),  # train on TF-IDF vectors w/ Naive Bayes classifier
])

In [24]:
pipeline.fit(X_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [3, 5286]